/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PesticideService } from "../pesticide.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PesticideCreateInput } from "./PesticideCreateInput";
import { Pesticide } from "./Pesticide";
import { PesticideFindManyArgs } from "./PesticideFindManyArgs";
import { PesticideWhereUniqueInput } from "./PesticideWhereUniqueInput";
import { PesticideUpdateInput } from "./PesticideUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PesticideControllerBase {
  constructor(
    protected readonly service: PesticideService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Pesticide })
  @nestAccessControl.UseRoles({
    resource: "Pesticide",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPesticide(
    @common.Body() data: PesticideCreateInput
  ): Promise<Pesticide> {
    return await this.service.createPesticide({
      data: data,
      select: {
        createdAt: true,
        id: true,
        productName: true,
        updatedAt: true,
        usageDetails: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Pesticide] })
  @ApiNestedQuery(PesticideFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Pesticide",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pesticides(@common.Req() request: Request): Promise<Pesticide[]> {
    const args = plainToClass(PesticideFindManyArgs, request.query);
    return this.service.pesticides({
      ...args,
      select: {
        createdAt: true,
        id: true,
        productName: true,
        updatedAt: true,
        usageDetails: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Pesticide })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Pesticide",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pesticide(
    @common.Param() params: PesticideWhereUniqueInput
  ): Promise<Pesticide | null> {
    const result = await this.service.pesticide({
      where: params,
      select: {
        createdAt: true,
        id: true,
        productName: true,
        updatedAt: true,
        usageDetails: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Pesticide })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Pesticide",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePesticide(
    @common.Param() params: PesticideWhereUniqueInput,
    @common.Body() data: PesticideUpdateInput
  ): Promise<Pesticide | null> {
    try {
      return await this.service.updatePesticide({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          productName: true,
          updatedAt: true,
          usageDetails: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Pesticide })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Pesticide",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePesticide(
    @common.Param() params: PesticideWhereUniqueInput
  ): Promise<Pesticide | null> {
    try {
      return await this.service.deletePesticide({
        where: params,
        select: {
          createdAt: true,
          id: true,
          productName: true,
          updatedAt: true,
          usageDetails: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
