/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EggBatchService } from "../eggBatch.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EggBatchCreateInput } from "./EggBatchCreateInput";
import { EggBatch } from "./EggBatch";
import { EggBatchFindManyArgs } from "./EggBatchFindManyArgs";
import { EggBatchWhereUniqueInput } from "./EggBatchWhereUniqueInput";
import { EggBatchUpdateInput } from "./EggBatchUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EggBatchControllerBase {
  constructor(
    protected readonly service: EggBatchService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EggBatch })
  @nestAccessControl.UseRoles({
    resource: "EggBatch",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEggBatch(
    @common.Body() data: EggBatchCreateInput
  ): Promise<EggBatch> {
    return await this.service.createEggBatch({
      data: data,
      select: {
        batchNumber: true,
        createdAt: true,
        id: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EggBatch] })
  @ApiNestedQuery(EggBatchFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EggBatch",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async eggBatches(@common.Req() request: Request): Promise<EggBatch[]> {
    const args = plainToClass(EggBatchFindManyArgs, request.query);
    return this.service.eggBatches({
      ...args,
      select: {
        batchNumber: true,
        createdAt: true,
        id: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EggBatch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EggBatch",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async eggBatch(
    @common.Param() params: EggBatchWhereUniqueInput
  ): Promise<EggBatch | null> {
    const result = await this.service.eggBatch({
      where: params,
      select: {
        batchNumber: true,
        createdAt: true,
        id: true,
        quantity: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EggBatch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EggBatch",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEggBatch(
    @common.Param() params: EggBatchWhereUniqueInput,
    @common.Body() data: EggBatchUpdateInput
  ): Promise<EggBatch | null> {
    try {
      return await this.service.updateEggBatch({
        where: params,
        data: data,
        select: {
          batchNumber: true,
          createdAt: true,
          id: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EggBatch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EggBatch",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEggBatch(
    @common.Param() params: EggBatchWhereUniqueInput
  ): Promise<EggBatch | null> {
    try {
      return await this.service.deleteEggBatch({
        where: params,
        select: {
          batchNumber: true,
          createdAt: true,
          id: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
