/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Produce as PrismaProduce,
  Pricing as PrismaPricing,
} from "@prisma/client";

export class ProduceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ProduceCountArgs, "select">): Promise<number> {
    return this.prisma.produce.count(args);
  }

  async produces<T extends Prisma.ProduceFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProduceFindManyArgs>
  ): Promise<PrismaProduce[]> {
    return this.prisma.produce.findMany<Prisma.ProduceFindManyArgs>(args);
  }
  async produce<T extends Prisma.ProduceFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProduceFindUniqueArgs>
  ): Promise<PrismaProduce | null> {
    return this.prisma.produce.findUnique(args);
  }
  async createProduce<T extends Prisma.ProduceCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProduceCreateArgs>
  ): Promise<PrismaProduce> {
    return this.prisma.produce.create<T>(args);
  }
  async updateProduce<T extends Prisma.ProduceUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProduceUpdateArgs>
  ): Promise<PrismaProduce> {
    return this.prisma.produce.update<T>(args);
  }
  async deleteProduce<T extends Prisma.ProduceDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProduceDeleteArgs>
  ): Promise<PrismaProduce> {
    return this.prisma.produce.delete(args);
  }

  async findPricings(
    parentId: string,
    args: Prisma.PricingFindManyArgs
  ): Promise<PrismaPricing[]> {
    return this.prisma.produce
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .pricings(args);
  }
}
