/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UsageGuidelineService } from "../usageGuideline.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UsageGuidelineCreateInput } from "./UsageGuidelineCreateInput";
import { UsageGuideline } from "./UsageGuideline";
import { UsageGuidelineFindManyArgs } from "./UsageGuidelineFindManyArgs";
import { UsageGuidelineWhereUniqueInput } from "./UsageGuidelineWhereUniqueInput";
import { UsageGuidelineUpdateInput } from "./UsageGuidelineUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UsageGuidelineControllerBase {
  constructor(
    protected readonly service: UsageGuidelineService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UsageGuideline })
  @nestAccessControl.UseRoles({
    resource: "UsageGuideline",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUsageGuideline(
    @common.Body() data: UsageGuidelineCreateInput
  ): Promise<UsageGuideline> {
    return await this.service.createUsageGuideline({
      data: data,
      select: {
        createdAt: true,
        description: true,
        guidelineTitle: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UsageGuideline] })
  @ApiNestedQuery(UsageGuidelineFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UsageGuideline",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async usageGuidelines(
    @common.Req() request: Request
  ): Promise<UsageGuideline[]> {
    const args = plainToClass(UsageGuidelineFindManyArgs, request.query);
    return this.service.usageGuidelines({
      ...args,
      select: {
        createdAt: true,
        description: true,
        guidelineTitle: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UsageGuideline })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UsageGuideline",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async usageGuideline(
    @common.Param() params: UsageGuidelineWhereUniqueInput
  ): Promise<UsageGuideline | null> {
    const result = await this.service.usageGuideline({
      where: params,
      select: {
        createdAt: true,
        description: true,
        guidelineTitle: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UsageGuideline })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UsageGuideline",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUsageGuideline(
    @common.Param() params: UsageGuidelineWhereUniqueInput,
    @common.Body() data: UsageGuidelineUpdateInput
  ): Promise<UsageGuideline | null> {
    try {
      return await this.service.updateUsageGuideline({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          guidelineTitle: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UsageGuideline })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UsageGuideline",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUsageGuideline(
    @common.Param() params: UsageGuidelineWhereUniqueInput
  ): Promise<UsageGuideline | null> {
    try {
      return await this.service.deleteUsageGuideline({
        where: params,
        select: {
          createdAt: true,
          description: true,
          guidelineTitle: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
