/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CropYieldPredictionService } from "../cropYieldPrediction.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CropYieldPredictionCreateInput } from "./CropYieldPredictionCreateInput";
import { CropYieldPrediction } from "./CropYieldPrediction";
import { CropYieldPredictionFindManyArgs } from "./CropYieldPredictionFindManyArgs";
import { CropYieldPredictionWhereUniqueInput } from "./CropYieldPredictionWhereUniqueInput";
import { CropYieldPredictionUpdateInput } from "./CropYieldPredictionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CropYieldPredictionControllerBase {
  constructor(
    protected readonly service: CropYieldPredictionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CropYieldPrediction })
  @nestAccessControl.UseRoles({
    resource: "CropYieldPrediction",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCropYieldPrediction(
    @common.Body() data: CropYieldPredictionCreateInput
  ): Promise<CropYieldPrediction> {
    return await this.service.createCropYieldPrediction({
      data: data,
      select: {
        createdAt: true,
        cropName: true,
        id: true,
        updatedAt: true,
        yieldPrediction: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CropYieldPrediction] })
  @ApiNestedQuery(CropYieldPredictionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CropYieldPrediction",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cropYieldPredictions(
    @common.Req() request: Request
  ): Promise<CropYieldPrediction[]> {
    const args = plainToClass(CropYieldPredictionFindManyArgs, request.query);
    return this.service.cropYieldPredictions({
      ...args,
      select: {
        createdAt: true,
        cropName: true,
        id: true,
        updatedAt: true,
        yieldPrediction: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CropYieldPrediction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CropYieldPrediction",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cropYieldPrediction(
    @common.Param() params: CropYieldPredictionWhereUniqueInput
  ): Promise<CropYieldPrediction | null> {
    const result = await this.service.cropYieldPrediction({
      where: params,
      select: {
        createdAt: true,
        cropName: true,
        id: true,
        updatedAt: true,
        yieldPrediction: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CropYieldPrediction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CropYieldPrediction",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCropYieldPrediction(
    @common.Param() params: CropYieldPredictionWhereUniqueInput,
    @common.Body() data: CropYieldPredictionUpdateInput
  ): Promise<CropYieldPrediction | null> {
    try {
      return await this.service.updateCropYieldPrediction({
        where: params,
        data: data,
        select: {
          createdAt: true,
          cropName: true,
          id: true,
          updatedAt: true,
          yieldPrediction: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CropYieldPrediction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CropYieldPrediction",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCropYieldPrediction(
    @common.Param() params: CropYieldPredictionWhereUniqueInput
  ): Promise<CropYieldPrediction | null> {
    try {
      return await this.service.deleteCropYieldPrediction({
        where: params,
        select: {
          createdAt: true,
          cropName: true,
          id: true,
          updatedAt: true,
          yieldPrediction: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
