/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AnalysisReport } from "./AnalysisReport";
import { AnalysisReportCountArgs } from "./AnalysisReportCountArgs";
import { AnalysisReportFindManyArgs } from "./AnalysisReportFindManyArgs";
import { AnalysisReportFindUniqueArgs } from "./AnalysisReportFindUniqueArgs";
import { CreateAnalysisReportArgs } from "./CreateAnalysisReportArgs";
import { UpdateAnalysisReportArgs } from "./UpdateAnalysisReportArgs";
import { DeleteAnalysisReportArgs } from "./DeleteAnalysisReportArgs";
import { AnalysisReportService } from "../analysisReport.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AnalysisReport)
export class AnalysisReportResolverBase {
  constructor(
    protected readonly service: AnalysisReportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AnalysisReport",
    action: "read",
    possession: "any",
  })
  async _analysisReportsMeta(
    @graphql.Args() args: AnalysisReportCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AnalysisReport])
  @nestAccessControl.UseRoles({
    resource: "AnalysisReport",
    action: "read",
    possession: "any",
  })
  async analysisReports(
    @graphql.Args() args: AnalysisReportFindManyArgs
  ): Promise<AnalysisReport[]> {
    return this.service.analysisReports(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AnalysisReport, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AnalysisReport",
    action: "read",
    possession: "own",
  })
  async analysisReport(
    @graphql.Args() args: AnalysisReportFindUniqueArgs
  ): Promise<AnalysisReport | null> {
    const result = await this.service.analysisReport(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AnalysisReport)
  @nestAccessControl.UseRoles({
    resource: "AnalysisReport",
    action: "create",
    possession: "any",
  })
  async createAnalysisReport(
    @graphql.Args() args: CreateAnalysisReportArgs
  ): Promise<AnalysisReport> {
    return await this.service.createAnalysisReport({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AnalysisReport)
  @nestAccessControl.UseRoles({
    resource: "AnalysisReport",
    action: "update",
    possession: "any",
  })
  async updateAnalysisReport(
    @graphql.Args() args: UpdateAnalysisReportArgs
  ): Promise<AnalysisReport | null> {
    try {
      return await this.service.updateAnalysisReport({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AnalysisReport)
  @nestAccessControl.UseRoles({
    resource: "AnalysisReport",
    action: "delete",
    possession: "any",
  })
  async deleteAnalysisReport(
    @graphql.Args() args: DeleteAnalysisReportArgs
  ): Promise<AnalysisReport | null> {
    try {
      return await this.service.deleteAnalysisReport(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
