/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { InsecticideService } from "../insecticide.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { InsecticideCreateInput } from "./InsecticideCreateInput";
import { Insecticide } from "./Insecticide";
import { InsecticideFindManyArgs } from "./InsecticideFindManyArgs";
import { InsecticideWhereUniqueInput } from "./InsecticideWhereUniqueInput";
import { InsecticideUpdateInput } from "./InsecticideUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class InsecticideControllerBase {
  constructor(
    protected readonly service: InsecticideService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Insecticide })
  @nestAccessControl.UseRoles({
    resource: "Insecticide",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createInsecticide(
    @common.Body() data: InsecticideCreateInput
  ): Promise<Insecticide> {
    return await this.service.createInsecticide({
      data: data,
      select: {
        createdAt: true,
        id: true,
        productName: true,
        updatedAt: true,
        usageDetails: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Insecticide] })
  @ApiNestedQuery(InsecticideFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Insecticide",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async insecticides(@common.Req() request: Request): Promise<Insecticide[]> {
    const args = plainToClass(InsecticideFindManyArgs, request.query);
    return this.service.insecticides({
      ...args,
      select: {
        createdAt: true,
        id: true,
        productName: true,
        updatedAt: true,
        usageDetails: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Insecticide })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Insecticide",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async insecticide(
    @common.Param() params: InsecticideWhereUniqueInput
  ): Promise<Insecticide | null> {
    const result = await this.service.insecticide({
      where: params,
      select: {
        createdAt: true,
        id: true,
        productName: true,
        updatedAt: true,
        usageDetails: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Insecticide })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Insecticide",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateInsecticide(
    @common.Param() params: InsecticideWhereUniqueInput,
    @common.Body() data: InsecticideUpdateInput
  ): Promise<Insecticide | null> {
    try {
      return await this.service.updateInsecticide({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          productName: true,
          updatedAt: true,
          usageDetails: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Insecticide })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Insecticide",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteInsecticide(
    @common.Param() params: InsecticideWhereUniqueInput
  ): Promise<Insecticide | null> {
    try {
      return await this.service.deleteInsecticide({
        where: params,
        select: {
          createdAt: true,
          id: true,
          productName: true,
          updatedAt: true,
          usageDetails: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
