/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FarmerProfileService } from "../farmerProfile.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FarmerProfileCreateInput } from "./FarmerProfileCreateInput";
import { FarmerProfile } from "./FarmerProfile";
import { FarmerProfileFindManyArgs } from "./FarmerProfileFindManyArgs";
import { FarmerProfileWhereUniqueInput } from "./FarmerProfileWhereUniqueInput";
import { FarmerProfileUpdateInput } from "./FarmerProfileUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FarmerProfileControllerBase {
  constructor(
    protected readonly service: FarmerProfileService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FarmerProfile })
  @nestAccessControl.UseRoles({
    resource: "FarmerProfile",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFarmerProfile(
    @common.Body() data: FarmerProfileCreateInput
  ): Promise<FarmerProfile> {
    return await this.service.createFarmerProfile({
      data: data,
      select: {
        bio: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FarmerProfile] })
  @ApiNestedQuery(FarmerProfileFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FarmerProfile",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async farmerProfiles(
    @common.Req() request: Request
  ): Promise<FarmerProfile[]> {
    const args = plainToClass(FarmerProfileFindManyArgs, request.query);
    return this.service.farmerProfiles({
      ...args,
      select: {
        bio: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FarmerProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FarmerProfile",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async farmerProfile(
    @common.Param() params: FarmerProfileWhereUniqueInput
  ): Promise<FarmerProfile | null> {
    const result = await this.service.farmerProfile({
      where: params,
      select: {
        bio: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FarmerProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FarmerProfile",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFarmerProfile(
    @common.Param() params: FarmerProfileWhereUniqueInput,
    @common.Body() data: FarmerProfileUpdateInput
  ): Promise<FarmerProfile | null> {
    try {
      return await this.service.updateFarmerProfile({
        where: params,
        data: data,
        select: {
          bio: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FarmerProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FarmerProfile",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFarmerProfile(
    @common.Param() params: FarmerProfileWhereUniqueInput
  ): Promise<FarmerProfile | null> {
    try {
      return await this.service.deleteFarmerProfile({
        where: params,
        select: {
          bio: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
