/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RestockService } from "../restock.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RestockCreateInput } from "./RestockCreateInput";
import { Restock } from "./Restock";
import { RestockFindManyArgs } from "./RestockFindManyArgs";
import { RestockWhereUniqueInput } from "./RestockWhereUniqueInput";
import { RestockUpdateInput } from "./RestockUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RestockControllerBase {
  constructor(
    protected readonly service: RestockService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Restock })
  @nestAccessControl.UseRoles({
    resource: "Restock",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRestock(
    @common.Body() data: RestockCreateInput
  ): Promise<Restock> {
    return await this.service.createRestock({
      data: data,
      select: {
        createdAt: true,
        id: true,
        quantity: true,
        restockDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Restock] })
  @ApiNestedQuery(RestockFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Restock",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async restocks(@common.Req() request: Request): Promise<Restock[]> {
    const args = plainToClass(RestockFindManyArgs, request.query);
    return this.service.restocks({
      ...args,
      select: {
        createdAt: true,
        id: true,
        quantity: true,
        restockDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Restock })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Restock",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async restock(
    @common.Param() params: RestockWhereUniqueInput
  ): Promise<Restock | null> {
    const result = await this.service.restock({
      where: params,
      select: {
        createdAt: true,
        id: true,
        quantity: true,
        restockDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Restock })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Restock",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRestock(
    @common.Param() params: RestockWhereUniqueInput,
    @common.Body() data: RestockUpdateInput
  ): Promise<Restock | null> {
    try {
      return await this.service.updateRestock({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          quantity: true,
          restockDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Restock })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Restock",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRestock(
    @common.Param() params: RestockWhereUniqueInput
  ): Promise<Restock | null> {
    try {
      return await this.service.deleteRestock({
        where: params,
        select: {
          createdAt: true,
          id: true,
          quantity: true,
          restockDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
