/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AgriculturalProductService } from "../agriculturalProduct.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AgriculturalProductCreateInput } from "./AgriculturalProductCreateInput";
import { AgriculturalProduct } from "./AgriculturalProduct";
import { AgriculturalProductFindManyArgs } from "./AgriculturalProductFindManyArgs";
import { AgriculturalProductWhereUniqueInput } from "./AgriculturalProductWhereUniqueInput";
import { AgriculturalProductUpdateInput } from "./AgriculturalProductUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AgriculturalProductControllerBase {
  constructor(
    protected readonly service: AgriculturalProductService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AgriculturalProduct })
  @nestAccessControl.UseRoles({
    resource: "AgriculturalProduct",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAgriculturalProduct(
    @common.Body() data: AgriculturalProductCreateInput
  ): Promise<AgriculturalProduct> {
    return await this.service.createAgriculturalProduct({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AgriculturalProduct] })
  @ApiNestedQuery(AgriculturalProductFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AgriculturalProduct",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async agriculturalProducts(
    @common.Req() request: Request
  ): Promise<AgriculturalProduct[]> {
    const args = plainToClass(AgriculturalProductFindManyArgs, request.query);
    return this.service.agriculturalProducts({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AgriculturalProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AgriculturalProduct",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async agriculturalProduct(
    @common.Param() params: AgriculturalProductWhereUniqueInput
  ): Promise<AgriculturalProduct | null> {
    const result = await this.service.agriculturalProduct({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        quantity: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AgriculturalProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AgriculturalProduct",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAgriculturalProduct(
    @common.Param() params: AgriculturalProductWhereUniqueInput,
    @common.Body() data: AgriculturalProductUpdateInput
  ): Promise<AgriculturalProduct | null> {
    try {
      return await this.service.updateAgriculturalProduct({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AgriculturalProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AgriculturalProduct",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAgriculturalProduct(
    @common.Param() params: AgriculturalProductWhereUniqueInput
  ): Promise<AgriculturalProduct | null> {
    try {
      return await this.service.deleteAgriculturalProduct({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
