/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  AgriculturalProduct as PrismaAgriculturalProduct,
} from "@prisma/client";

export class AgriculturalProductServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AgriculturalProductCountArgs, "select">
  ): Promise<number> {
    return this.prisma.agriculturalProduct.count(args);
  }

  async agriculturalProducts<T extends Prisma.AgriculturalProductFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AgriculturalProductFindManyArgs>
  ): Promise<PrismaAgriculturalProduct[]> {
    return this.prisma.agriculturalProduct.findMany<Prisma.AgriculturalProductFindManyArgs>(
      args
    );
  }
  async agriculturalProduct<T extends Prisma.AgriculturalProductFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AgriculturalProductFindUniqueArgs>
  ): Promise<PrismaAgriculturalProduct | null> {
    return this.prisma.agriculturalProduct.findUnique(args);
  }
  async createAgriculturalProduct<
    T extends Prisma.AgriculturalProductCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.AgriculturalProductCreateArgs>
  ): Promise<PrismaAgriculturalProduct> {
    return this.prisma.agriculturalProduct.create<T>(args);
  }
  async updateAgriculturalProduct<
    T extends Prisma.AgriculturalProductUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.AgriculturalProductUpdateArgs>
  ): Promise<PrismaAgriculturalProduct> {
    return this.prisma.agriculturalProduct.update<T>(args);
  }
  async deleteAgriculturalProduct<
    T extends Prisma.AgriculturalProductDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.AgriculturalProductDeleteArgs>
  ): Promise<PrismaAgriculturalProduct> {
    return this.prisma.agriculturalProduct.delete(args);
  }
}
