/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  FinancialProjection as PrismaFinancialProjection,
} from "@prisma/client";

export class FinancialProjectionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FinancialProjectionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.financialProjection.count(args);
  }

  async financialProjections<T extends Prisma.FinancialProjectionFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.FinancialProjectionFindManyArgs>
  ): Promise<PrismaFinancialProjection[]> {
    return this.prisma.financialProjection.findMany<Prisma.FinancialProjectionFindManyArgs>(
      args
    );
  }
  async financialProjection<T extends Prisma.FinancialProjectionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.FinancialProjectionFindUniqueArgs>
  ): Promise<PrismaFinancialProjection | null> {
    return this.prisma.financialProjection.findUnique(args);
  }
  async createFinancialProjection<
    T extends Prisma.FinancialProjectionCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.FinancialProjectionCreateArgs>
  ): Promise<PrismaFinancialProjection> {
    return this.prisma.financialProjection.create<T>(args);
  }
  async updateFinancialProjection<
    T extends Prisma.FinancialProjectionUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.FinancialProjectionUpdateArgs>
  ): Promise<PrismaFinancialProjection> {
    return this.prisma.financialProjection.update<T>(args);
  }
  async deleteFinancialProjection<
    T extends Prisma.FinancialProjectionDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.FinancialProjectionDeleteArgs>
  ): Promise<PrismaFinancialProjection> {
    return this.prisma.financialProjection.delete(args);
  }
}
